---
title: "Early Stopping"
date: "`r format(Sys.time(), '%d %B, %Y')`"
author: Jie Bao
output:
  html_document:
    fig_caption: yes
  pdf_document: default
---

```{r, echo=FALSE, message=FALSE}
library(ggplot2)
library(dplyr)
library(RODBC)
library(lubridate)
library(bigrquery)
library(rstan)
library(shinystan)
fontsize <- 15
theme_set(theme_bw(fontsize))
setwd('~/project/ghe/early-stopping')
```



```{r bf, echo=FALSE, cache=TRUE, eval=TRUE}
dat <- read.csv('bayes_factor.csv', header=FALSE)
days <- 20
sims <- 100
dat$day <- rep(1:days, sims)
dat$sim <- rep(1:sims, each=days)
ggplot(dat,aes(day,V1,colour=sim,group=sim)) + geom_line() + geom_hline(yintercept = 1)
```

```{r stan, echo=FALSE, eval=TRUE}
df <- read.csv('data/simulated_kpi.csv')
fit_data <- list(Nc=sum(df$variant=='A'), 
				         Nt=sum(df$variant=='B'), 
				         x=df$normal_same[df$variant=='A'], 
				         y=df$normal_same[df$variant=='B'])
fit <- stan(file='normal_kpi.stan', data=fit_data, iter=25000, chains=4)
launch_shinystan(fit)
```



```{r myfilter, echo=FALSE, message=FALSE, eval=TRUE}
#kpi <- read.csv('size39_sales_kpi_over_time.csv')
#kpi$return_rate <- kpi$ARTICLES_RETURNED/kpi$ARTICLES_ORDERED
#hist(kpi$return_rate)

# simulation
N <- 1000
dat <- rep(0,N)
for (i in 1:N) {
  num <- runif(1)
  if (num < 0.3)
    dat[i] <- 0
  else if (num < 0.6)
    dat[i] <- 1
  else
    dat[i] <- rbeta(1,5,3)
}

model_code <- "
data {
  int<lower=0> N;                 // sample size
  real<lower=0,upper=1> rate[N];  // ratio metric
}

parameters {
  simplex[3] theta;             // weights
  real<lower=0> alpha;         // beta distribution
  real<lower=0> beta;          // beta distribution
}

model {
  // Likelihood
  for (i in 1:N) {
    if (rate[i] == 0)
      target += log(theta[1]);
    else if (rate[i] == 1)
      target += log(theta[3]);
    else
      target += log(theta[2]) + beta_lpdf(rate[i] | alpha, beta);
  }
}
"
#fit_data <- list(N=sum(!is.na(kpi$return_rate)), 
#				         rate=kpi$return_rate[!is.na(kpi$return_rate)])
fit_data <- list(N=N, rate=dat)
fit <- stan(model_code = model_code, data=fit_data, iter=25000, chains=4, algorithm = 'NUTS')
```



```{r rate, echo=FALSE, eval=TRUE}
kpi <- read.csv('size39_sales_kpi_over_time.csv')
kpi_cleaned <- subset(kpi, ARTICLES_ORDERED!=0)
fit_data <- list(Nc=sum(kpi_cleaned$variant=='hide'),
                 Nt=sum(kpi_cleaned$variant=='show'),
                 t_c=kpi_cleaned$ARTICLES_ORDERED[kpi_cleaned$variant=='hide'],
                 t_t=kpi_cleaned$ARTICLES_ORDERED[kpi_cleaned$variant=='show'],
                 s_c=kpi_cleaned$ARTICLES_RETURNED[kpi_cleaned$variant=='hide'],
                 s_t=kpi_cleaned$ARTICLES_RETURNED[kpi_cleaned$variant=='show'])
fit <- stan(file='rate_kpi.stan', data=fit_data, iter=25000, chains=4, algorithm = 'NUTS', control = list(adapt_delta=0.99))
```

```{r sim, echo=FALSE, eval=TRUE}
rtpois <- function(N, lambda)
  qpois(runif(N, dpois(0, lambda), 1), lambda)

mu <- 1
lambda <- 3
n <- 1000
sims <- 100
m <- NULL
for (s in 1:sims) {
  if (s%%10 == 0)
    print(s)
  df <- NULL
  for (i in 1:n) {
    df <- rbind(df, data.frame(entity=i,val=rnorm(rtpois(1,lambda),mean=mu)))
  }
  df.unique <- df %>% group_by(entity) %>% summarise(v=sum(val))
  m <- c(m,mean(df.unique$v))
}
hist(m)
lambda/(1-exp(-lambda))*mu
```

```{r bunchbox, echo=FALSE, eval=TRUE}
#fname <- '~/slurm/src/early-stopping/group_sequential/group_sequential_normal_same_20170216.csv'
#fname <- '~/slurm/src/early-stopping/group_sequential/group_sequential_normal_shifted_20170220.csv'
fname <- 'docs/group_sequential_normal_shifted_20170227.csv'
dat <- read.csv(fname, header = FALSE)
stop <- dat %>% group_by(V1) %>% arrange(desc(V3),V2) %>% slice(1)
stop$time <- stop$V2 
stop$time[stop$V3=='False'] <- 19
#mean(stop$time)/20 # % runtime

merged <- merge(dat[,c('V1','V2','V4')], stop[,c('V1','time')], by.x=c('V1','V2'), by.y=c('V1','time'))
#delta <- 3/(1-exp(-3))*1
delta <- 1
abs(mean(merged$V4)-delta)/delta
```

```{r bunchbox, echo=FALSE, eval=TRUE}
fname <- 'docs/bayes_factor_normal_same_cauchy_1.0_20170222.csv'
dat <- read.csv(fname, header = FALSE)
dat <- subset(dat, V3<1/3)
stop <- dat %>% group_by(V1) %>% arrange(V2) %>% slice(1)
#stop$time <- stop$V2 
#stop$time[stop$V3=='False'] <- 19
#mean(stop$time)/20 # % runtime

#merged <- merge(dat[,c('V1','V2','V4')], stop[,c('V1','time')], by.x=c('V1','V2'), by.y=c('V1','time'))
#delta <- 3/(1-exp(-3))*1
#abs(mean(merged$V4)-delta)/delta
```

```{r bp, echo=FALSE, eval=TRUE}
fname <- 'docs/precision_normal_shifted_20170227.csv'
dat <- read.csv(fname, header = FALSE)
dat <- subset(dat, V4<0.07)
stop <- dat %>% group_by(V1) %>% arrange(V2) %>% slice(1)
#stop$time <- stop$V2 
#stop$time[stop$V3=='False'] <- 19
#mean(stop$time)/20 # % runtime

#merged <- merge(dat[,c('V1','V2','V3')], stop[,c('V1','time')], by.x=c('V1','V2'), by.y=c('V1','time'))
#delta <- 3/(1-exp(-3))*1
delta <- 1
abs(mean(stop$V3)-delta)/delta
```